[package]
name = "ps2hdd-sys"
version = "0.1.0"
authors = ["Jessica Stokes <hello@jessicastokes.net>"]
edition = "2018"

[dependencies]

[dev-dependencies]
libc = "0.2.78"
serial_test = "0.5.0"

[build-dependencies]
bindgen = "0.55.1"
meson = "1.0.0"
