[package]
name = "ps2hdd"
version = "0.1.0"
authors = ["Jessica Stokes <hello@jessicastokes.net>"]
edition = "2018"

[dependencies]
libc = "0.2.78"

[dependencies.ps2hdd-sys]
  path = "../ps2hdd-sys"

[dev-dependencies]
serial_test = "0.5.0"