name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - &CHECKOUT
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - &PYTHON
        name: Set up Python
        uses: actions/setup-python@v1

      # pfsshell uses meson and ninja; we integrated them into the Rust build, but still need to install them
      - &PYTHON_DEPS
        name: Set up meson and ninja
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            meson
            ninja

      - name: Build
        run: cargo build --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - *CHECKOUT

      - *PYTHON

      - *PYTHON_DEPS

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - *CHECKOUT

      - *PYTHON

      - *PYTHON_DEPS

      - name: Test & Coverage Reporting
        uses: actions-rs/tarpaulin@v0.1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
