name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1

    # pfsshell uses meson and ninja; we integrated them into the Rust build, but still need to install them
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          meson
          ninja

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
